### ISSUE TITLE
Error while loading admin dashboard

### ISSUE THREAD

**Issue by saquibrazak** [inmanjlai/codeTracker#23]
I get the following error while loading admin dashboard

pocketbase.umd.js:1 Uncaught (in promise) ClientResponseError 0: The request was autocancelled. You can find more info in https://github.com/pocketbase/js-sdk#auto-cancellation.
    at new ClientResponseError (pocketbase.umd.js:1:2541)
    at pocketbase.umd.js:1:45583
    at async getUser (admin.js:76:53)

**Comment by inmanjlai** [comment]
This is happening because, for some reason, there are multiple duplicate requests being made. So pocketbase is cancelling duplicate requests. It is a non-issue, but I believe it will be fixed with the future rewrite.
